### ISSUE TITLE
Frage bzg. IDesignerHost

### ISSUE THREAD

**Issue by AdmiralSnyder** [ReneVogt/WindowsFormsExpander#9]
Hallo René,
keine ahnung, ob ich die Frage auch anders stellen kann, hab keine direkte kontaktmöglichkeit gefunden:
Du hast in einer stackoverflow frage ( https://stackoverflow.com/questions/33542662/draw-adornments-on-windows-forms-controls-in-visual-studio-designer-from-an-exte ) erwähnt, dass du eine extension gebaut hast, die winforms-designer überwacht.
ich will gerade etwas ähnliches bauen (nicht UI adornen, sondern über nen typedescriptor die lokalisierung "umgehen" - gibt's die möglichkeit, dass ich mir den mechanismus zum Ankabeln an beliebige Designer bei dir ausleihen kann?

vielen Dank,
Alex

**Comment by ReneVogt** [comment]
Hi Alex,

vielleicht ist die Frage tatsächlich auf StackOverflow besser aufgehoben. Was genau willst du denn tun und was fehlt dir? 

Um an den Designer zu kommen, verwende ich `IDesignerEventService` (bekommst du von `GetService` bzw. `GetServiceAsync` aus deinem Extension-Package). Dieses Interface hat ein `DesignerCreated`-Event, in dem du dann den `IDesignerHost` für den neu geöffneten Designer bekommst.
Ich hab das bisher nur für Windows-Forms-Designer gemacht.

Ich hoffe, das hilft erstmal. Ansonsten frag eher auf SO mit einer genaueren Beschreibung, was du bisher hast und wo du nicht weiter kommst.

**Comment by AdmiralSnyder** [comment]
hallo, danke. ich dachte, weil du bei SO nicht mehr aktiv bist seit ... 4 jahren, wenn ich mich richtig erinnere, frag ich lieber hier.
habs hinbekommen, denke ich. weißt du zufällig aus dem Kopf, ob es einen IDesignerHost pro designer gibt, oder ob das für alle winforms-designer derselbe ist?
ooh, und über den IDesignerEventService gehen ist viiiel eleganter als über DTE.Events.WindowEvents.WindowCreated zu gehen :-) - von daher nochmal: danke.

(Werbung): bitte komm in den C# discord. Der beste Platz im internet: https://discord.gg/csharp
